language: python

python:
  - "2.7"

sudo: false

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

env:
  - PIO_BRD: "'-b uno'"         # arduino uno
  - PIO_BRD: "'-b due'"         # arduino due
  - PIO_BRD: "'-b zero'"        # arduino zero
  - PIO_BRD: "'-b teensy30 -b teensy31 -b teensy35 -b teensy36'" # teensy
  - PIO_BRD: "'-b esp01 -b nodemcuv2 -b espduino'"               # esp8266
  - PIO_BRD: "'-b rfduino'"     # nrf51
  - PIO_BRD: "'-b lenny'"       # pic32mx
  - PIO_BRD: "'-b genuino101'"  # intel curie

before_script:
  - platformio init $PIO_BRD

script:
  - platformio ci --lib="." $PIO_BRD ./examples/DS18x20_Temperature/DS18x20_Temperature.ino
  - platformio ci --lib="." $PIO_BRD ./examples/DS2408_Switch/DS2408_Switch.ino
  - platformio ci --lib="." $PIO_BRD ./examples/DS250x_PROM/DS250x_PROM.ino
  - platformio ci --lib="." $PIO_BRD ./examples/DS2438_BatMon/DS2438_BatMon.ino

#elif defined(NRF52) /* arduino primo */
#elif defined(NRF51) /* red bear blend, should be good for all nrf51x chips */
